name: my-front
on: #언제 git action이 되냐
  push: #push될때
    branches: #어떤브랜치에?
      - main #메인브랜치에
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} #이친구들은 다 깃허브의 settings - secrets에서 작성! 절대 여기다적지마시오
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #이친구들은 다 깃허브의 settings - secrets에서 작성! 절대 여기다적지마시오
      AWS_REGION: 'ap-northeast-2'

    steps:
      - name: Checkout source code.
        uses: actions/checkout@master

      - name: Upload binary to S3 bucket
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --exclude '*' --include 'index.html'
        env:
          AWS_S3_BUCKET: ${{ secrets.BUCKET_NAME }} #이친구들은 다 깃허브의 settings - secrets에서 작성! 절대 여기다적지마시오

      - name: Invalidate cache CloudFront
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }} #이친구들은 다 깃허브의 settings - secrets에서 작성! 절대 여기다적지마시오
          PATHS: '/index.html'
        continue-on-error: true